image: alpine/edge
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
sources:
  - git+ssh://git@git.sr.ht/~mattmundell/libtheia-dummy
tasks:
  - check: |
      cd libtheia-dummy
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      cd libtheia-dummy
      git remote add github git@github.com:mattmundell/libtheia-dummy.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
